import { Link } from "react-router-dom";

const G = "#c9973a", GSFT = "#f0d080", TXT = "#fdf0d5", MUTED = "#b89060", DEEP = "#0a0300";

const TOOLS = [
  {
    icon: "🔮",
    title: "Janma Kundali — Birth Chart",
    desc: "Enter your birth date, time, and place. We compute your complete Vedic birth chart using Swiss Ephemeris — all 9 planets in their precise sidereal positions, all 12 houses by Whole Sign, nakshatra and pada for each planet, Vimshottari dasha timeline, yogas present in your chart, and classical remedies for every planet. Then a full AI-generated Pandit's reading synthesises it all into a readable interpretation.",
    link: "/kundali",
    cta: "Open Birth Chart →",
  },
  {
    icon: "💑",
    title: "Kundali Matching — Ashtakoot Milan",
    desc: "The classical 8-fold compatibility system used in Vedic marriage matching. Enter both birth charts and receive a complete Ashtakoot report (all 8 kootas scored out of 36), Rajju and Vedha analysis, Mangal dosha check for both persons, extended Mahendra and Stree-Deergha kootas, and a detailed AI compatibility reading.",
    link: "/matching",
    cta: "Open Kundali Matching →",
  },
  {
    icon: "🔢",
    title: "Vedic Numerology",
    desc: "Calculate your Moolank (birth number), Bhagyank (destiny number), Namank (name number by Chaldean system), and Personal Year. The reading focuses on the relationship between your numbers — how they support or challenge each other — rather than describing each number in isolation. Includes a full AI reading across past, present, and next personal years.",
    link: "/numerology",
    cta: "Open Numerology →",
  },
];

const FAQ = [
  {
    q: "Is this really free?",
    a: "Yes. No signup, no subscription, no limit. Every feature on this site is permanently free. Jyotish is wisdom — it should not be locked behind a paywall.",
  },
  {
    q: "How accurate are the calculations?",
    a: "The planetary positions use Swiss Ephemeris, the same astronomical library used by professional astrology software worldwide. We use Lahiri Ayanamsa (the standard for Vedic / sidereal astrology) and Whole Sign houses, the oldest and most classical house system.",
  },
  {
    q: "What is the AI reading?",
    a: "The AI reading is generated by a large language model trained on classical Jyotish texts — Brihat Parashara Hora Shastra, Phaladeepika, Saravali, and others. It synthesises your chart data into natural-language paragraphs. Think of it as a very knowledgeable Jyotishi writing a summary — not a replacement for a human consultation on life decisions.",
  },
  {
    q: "Why sidereal and not tropical?",
    a: "Vedic Jyotish uses the sidereal zodiac, which tracks the actual positions of planets against the fixed stars. The tropical zodiac (used in Western astrology) tracks the seasons. These diverge by about 23–24 degrees — a meaningful difference. If you were born in late March, your sidereal Sun is still in Pisces, not Aries. Both systems have value; this site focuses on the Vedic tradition.",
  },
  {
    q: "Can I share my chart with someone?",
    a: "Yes. After generating your chart or reading, the URL updates to encode your birth details. Copy that URL and send it — anyone who opens it will see the same chart automatically generated.",
  },
  {
    q: "What is Lahiri Ayanamsa?",
    a: "Ayanamsa is the correction applied to convert tropical planetary positions to sidereal. There are several ayanamsa systems (Lahiri, Raman, Krishnamurti). Lahiri — also called the Chitrapaksha ayanamsa — is the official standard of the Indian government and the most widely used by Vedic astrologers worldwide.",
  },
];

export default function About() {
  return (
    <div style={{ background: DEEP, minHeight: "100vh", color: TXT, fontFamily: "Georgia, serif" }}>

      {/* Hero */}
      <section style={{ textAlign: "center", padding: "80px 24px 60px",
                        background: "linear-gradient(160deg,#1a0500 0%,#0a0200 60%,#001408 100%)",
                        borderBottom: `1px solid ${G}33` }}>
        <div style={{ fontSize: 64, color: G, lineHeight: 1, marginBottom: 12 }}>ॐ</div>
        <h1 style={{ fontSize: 48, fontWeight: "bold", color: GSFT, margin: "0 0 12px", letterSpacing: 2 }}>
          About Pavitra Jyotish
        </h1>
        <p style={{ color: G, fontSize: 18, margin: "0 0 20px", letterSpacing: 2 }}>
          पवित्र ज्योतिष — Pure Vedic Astrology
        </p>
        <p style={{ color: MUTED, fontSize: 16, maxWidth: 640, margin: "0 auto", lineHeight: 1.9,
                    fontFamily: "system-ui, sans-serif" }}>
          A free, classical Vedic astrology tool built for everyone — whether you are in Kathmandu,
          Delhi, London, or anywhere on Earth.
        </p>
      </section>

      <div style={{ maxWidth: 860, margin: "0 auto", padding: "60px 24px 80px" }}>

        {/* Mission */}
        <section style={S.section}>
          <h2 style={S.sectionTitle}>Our Mission</h2>
          <p style={S.body}>
            Jyotish — the eye of the Vedas — is one of humanity's oldest and most precise
            systems for understanding the self and time. For millennia it was passed freely
            from teacher to student as part of the Vedic tradition. We believe that wisdom
            should remain free.
          </p>
          <p style={S.body}>
            Pavitra Jyotish exists to give every person on Earth access to a complete,
            classical Vedic reading — with no account required, no subscription, no payment.
            Whether you are a student curious about your chart, a parent checking compatibility
            before a marriage, or a practitioner wanting a second reference — this tool is yours.
          </p>
          <blockquote style={S.quote}>
            "Jyotish is the eye of the Vedas. It reveals the path of dharma,
            illuminates karma, and shows the way to moksha. It belongs to all."
            <span style={S.quoteSource}>— Brihat Parashara Hora Shastra</span>
          </blockquote>
        </section>

        {/* Tools */}
        <section style={S.section}>
          <h2 style={S.sectionTitle}>What We Offer</h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            {TOOLS.map(tool => (
              <div key={tool.title} style={S.toolCard}>
                <div style={{ fontSize: 32, marginBottom: 10 }}>{tool.icon}</div>
                <h3 style={S.toolTitle}>{tool.title}</h3>
                <p style={S.toolDesc}>{tool.desc}</p>
                <Link to={tool.link} style={S.toolLink}>{tool.cta}</Link>
              </div>
            ))}
          </div>
        </section>

        {/* Tradition */}
        <section style={S.section}>
          <h2 style={S.sectionTitle}>The Classical Tradition</h2>
          <p style={S.body}>
            Every calculation and interpretation on this site is grounded in the texts of the
            classical Jyotish tradition:
          </p>
          <ul style={S.ul}>
            <li style={S.li}><strong style={{ color: GSFT }}>Brihat Parashara Hora Shastra</strong> — the foundational text of Vedic astrology, attributed to Maharishi Parashara</li>
            <li style={S.li}><strong style={{ color: GSFT }}>Phaladeepika</strong> — classical text on planetary results and house analysis</li>
            <li style={S.li}><strong style={{ color: GSFT }}>Saravali</strong> — planetary dignities, yogas, and their effects</li>
            <li style={S.li}><strong style={{ color: GSFT }}>Jataka Parijata</strong> — classical source on birth chart interpretation</li>
          </ul>
          <p style={{ ...S.body, marginTop: 16 }}>
            Calculations use <strong style={{ color: GSFT }}>Swiss Ephemeris</strong> (the gold standard in astronomical precision),
            <strong style={{ color: GSFT }}> Lahiri Ayanamsa</strong> (the official Indian government standard for sidereal conversion),
            and <strong style={{ color: GSFT }}>Whole Sign houses</strong> (the oldest and most classical house system in Jyotish).
          </p>
        </section>

        {/* Technology */}
        <section style={S.section}>
          <h2 style={S.sectionTitle}>The Technology</h2>
          <p style={S.body}>
            The backend is a Python API (FastAPI) that uses the Swiss Ephemeris Python bindings to
            compute precise planetary positions for any date, time, and location since 13,000 BCE.
            The AI reading layer uses a large language model prompted with classical Jyotish knowledge
            to synthesise the chart data into natural language.
          </p>
          <p style={S.body}>
            The frontend is a React application deployed on Netlify. The API runs on Render.
            The site is entirely open — no tracking beyond basic analytics, no data stored.
          </p>
        </section>

        {/* FAQ */}
        <section style={S.section}>
          <h2 style={S.sectionTitle}>Frequently Asked Questions</h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
            {FAQ.map(({ q, a }) => (
              <div key={q} style={S.faqItem}>
                <div style={S.faqQ}>✦ {q}</div>
                <div style={S.faqA}>{a}</div>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section style={{ textAlign: "center", padding: "40px 0 0" }}>
          <div style={{ fontSize: 40, color: G, marginBottom: 16 }}>ॐ</div>
          <p style={{ color: MUTED, fontSize: 15, marginBottom: 28, fontFamily: "system-ui,sans-serif" }}>
            Ready to see your chart?
          </p>
          <div style={{ display: "flex", gap: 16, justifyContent: "center", flexWrap: "wrap" }}>
            <Link to="/kundali" style={S.ctaBtn}>Get My Birth Chart</Link>
            <Link to="/matching" style={{ ...S.ctaBtn, background: "transparent",
              border: `1px solid ${G}55`, color: MUTED }}>Kundali Matching</Link>
          </div>
        </section>

      </div>

      <footer style={{ textAlign: "center", padding: "32px 24px", borderTop: `1px solid ${G}22` }}>
        <p style={{ color: MUTED, fontSize: 13, fontFamily: "system-ui,sans-serif" }}>
          Pavitra Jyotish · पवित्र ज्योतिष · Classical Vedic Astrology · Built with devotion
        </p>
      </footer>
    </div>
  );
}

const S = {
  section:      { marginBottom: 48 },
  sectionTitle: { fontSize: 28, fontWeight: "bold", color: GSFT, margin: "0 0 20px",
                  borderBottom: `1px solid ${G}33`, paddingBottom: 12 },
  body:         { color: TXT, fontSize: 15, lineHeight: 1.9, margin: "0 0 16px",
                  fontFamily: "system-ui, sans-serif" },
  quote:        { borderLeft: `3px solid ${G}`, paddingLeft: 20, margin: "24px 0",
                  color: MUTED, fontSize: 16, fontStyle: "italic", lineHeight: 1.9,
                  display: "flex", flexDirection: "column", gap: 10 },
  quoteSource:  { color: G, fontSize: 12, fontStyle: "normal", fontFamily: "system-ui,sans-serif",
                  letterSpacing: 1 },
  toolCard:     { background: "#150900", border: `1px solid ${G}33`, borderRadius: 14,
                  padding: "24px 28px" },
  toolTitle:    { color: GSFT, fontSize: 20, fontWeight: "bold", margin: "0 0 10px" },
  toolDesc:     { color: MUTED, fontSize: 14, lineHeight: 1.8, margin: "0 0 16px",
                  fontFamily: "system-ui, sans-serif" },
  toolLink:     { display: "inline-block", padding: "10px 22px",
                  background: `linear-gradient(135deg,#6b3a00,#3d1500)`,
                  border: `1px solid ${G}`, borderRadius: 8, color: GSFT, fontSize: 13,
                  fontWeight: "bold", textDecoration: "none", letterSpacing: 1 },
  ul:           { paddingLeft: 0, listStyle: "none", margin: 0 },
  li:           { color: MUTED, fontSize: 14, lineHeight: 1.8, padding: "6px 0",
                  fontFamily: "system-ui, sans-serif", borderBottom: `1px solid ${G}11` },
  faqItem:      { background: "#0f0500", borderRadius: 10, padding: "18px 20px", marginBottom: 8,
                  border: `1px solid ${G}22` },
  faqQ:         { color: GSFT, fontSize: 15, fontWeight: "bold", marginBottom: 8 },
  faqA:         { color: MUTED, fontSize: 14, lineHeight: 1.8, fontFamily: "system-ui, sans-serif" },
  ctaBtn:       { padding: "14px 32px", background: `linear-gradient(135deg,#6b3a00,#3d1500)`,
                  border: `1px solid ${G}`, borderRadius: 10, color: GSFT, fontSize: 15,
                  fontWeight: "bold", textDecoration: "none", display: "inline-block", letterSpacing: 1 },
};
